name: olly_olly_flutter_test
description: "Olly Olly Flutter Test"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^14.6.2
  injectable: ^2.5.2
  provider: ^6.1.5+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true
  generate: true